// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJEu9aUpmN8zj2bCiQ4eCvgNX6Pjl4XaE',
    appId: '1:167294962056:web:c796d8e725a84705c3923d',
    messagingSenderId: '167294962056',
    projectId: 'congressional-app-challe-5046a',
    authDomain: 'congressional-app-challe-5046a.firebaseapp.com',
    storageBucket: 'congressional-app-challe-5046a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJpwjmJnzvjTeQQCMyD_PjuVWB_EgyWI',
    appId: '1:167294962056:android:6f04fcd320c5ab70c3923d',
    messagingSenderId: '167294962056',
    projectId: 'congressional-app-challe-5046a',
    storageBucket: 'congressional-app-challe-5046a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64qZW65XYCuL0Bb0lfmb6Aw_eQ8xl8EM',
    appId: '1:167294962056:ios:68ab5491b0532ee0c3923d',
    messagingSenderId: '167294962056',
    projectId: 'congressional-app-challe-5046a',
    storageBucket: 'congressional-app-challe-5046a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64qZW65XYCuL0Bb0lfmb6Aw_eQ8xl8EM',
    appId: '1:167294962056:ios:68ab5491b0532ee0c3923d',
    messagingSenderId: '167294962056',
    projectId: 'congressional-app-challe-5046a',
    storageBucket: 'congressional-app-challe-5046a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJEu9aUpmN8zj2bCiQ4eCvgNX6Pjl4XaE',
    appId: '1:167294962056:web:ef904213cee3e886c3923d',
    messagingSenderId: '167294962056',
    projectId: 'congressional-app-challe-5046a',
    authDomain: 'congressional-app-challe-5046a.firebaseapp.com',
    storageBucket: 'congressional-app-challe-5046a.appspot.com',
  );
}
